### ISSUE TITLE
test failed.

### ISSUE THREAD

**Issue by r1se** [SonarQubeCommunity/sonar-pdf-report#21]
Hello, i'm try build release 1.4 use maven. After i'm type mvn package, on test unit i'get error:

Tests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2.3 sec <<< FAIL
URE!
metricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)  Time elapsed:
1.874 sec  <<< FAILURE!
java.lang.AssertionError: Metric profile is not provided expected:<true> but was
:<false>
        at org.testng.Assert.fail(Assert.java:84)
        at org.testng.Assert.failNotEquals(Assert.java:438)
        at org.testng.Assert.assertTrue(Assert.java:32)
        at org.sonar.report.pdf.test.MetricsTest.metricsShouldBeConsistent(Metri
csTest.java:58)

Results :
Failed tests:   metricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)
: Metric profile is not provided expected:<true> but was:<false>

Tests run: 5, Failures: 1, Errors: 0, Skipped: 1

Enviroments:
Apache Maven 3.3.9 
Java version: 1.8.0_71
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by adomenech73** [comment]
I have the same problem, as workaround I skip tests with

```Bash
mvn package -Dmaven.test.skip=true
```

**Comment by designerferro** [comment]
This won't work o. Versions after 5.1 because of SonarQube API change.

**Comment by adomenech73** [comment]
@MacXatu So what can we use in it's place to get some kind of offline reporting?

**Comment by designerferro** [comment]
@adomenech73 
there is always the payed version or SonarQube which includes PDF reports.

I'm looking at the Http/Json to get a tailor suited HTML printable report.
