### ISSUE TITLE
Sonar report issue 

### ISSUE THREAD

**Issue by vishnudesam** [SonarQubeCommunity/sonar-pdf-report#33]
when i am running sonar report getting errror

.\.sonar\batch-report\issues-36.pb (The process cannot access the file because it is being used by another process)

ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.squidbridge.api.AnalysisException: SonarQube is unable to analyze file : 'C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin
        at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:93)
        at org.sonar.java.ast.JavaAstScanner.scan(JavaAstScanner.java:67)
        at org.sonar.java.JavaSquid.scanSources(JavaSquid.java:136)
        at org.sonar.java.JavaSquid.scan(JavaSquid.java:129)
        at org.sonar.plugins.java.JavaSquidSensor.analyse(JavaSquidSensor.java:90)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: org.sonar.core.util.ContextException: Unable to write issue | file=C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin\mmtel\TAS\.\.son
        at org.sonar.core.util.ContextException.of(ContextException.java:125)
        at org.sonar.scanner.protocol.output.ScannerReportWriter.appendComponentIssue(ScannerReportWriter.java:79)
        at org.sonar.batch.issue.ModuleIssues.write(ModuleIssues.java:148)
        at org.sonar.batch.issue.ModuleIssues.initAndAddIssue(ModuleIssues.java:97)
        at org.sonar.batch.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:180)
        at org.sonar.api.batch.sensor.issue.internal.DefaultIssue.doSave(DefaultIssue.java:156)
        at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
        at org.sonar.java.JavaIssue.save(JavaIssue.java:80)
        at org.sonar.java.SonarComponents.reportIssueAfterSQ52(SonarComponents.java:231)
        at org.sonar.java.SonarComponents.reportIssue(SonarComponents.java:210)
        at org.sonar.java.model.DefaultJavaFileScannerContext.reportIssue(DefaultJavaFileScannerContext.java:126)
        at org.sonar.java.model.DefaultJavaFileScannerContext.reportIssue(DefaultJavaFileScannerContext.java:121)
        at org.sonar.java.checks.UndocumentedApiCheck.visitNode(UndocumentedApiCheck.java:132)
        at org.sonar.java.checks.UndocumentedApiCheck.visitMethod(UndocumentedApiCheck.java:123)
        at org.sonar.java.model.declaration.MethodTreeImpl.accept(MethodTreeImpl.java:218)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:43)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:37)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.visitClass(BaseTreeVisitor.java:69)
        at org.sonar.java.checks.UndocumentedApiCheck.visitClass(UndocumentedApiCheck.java:110)
        at org.sonar.java.model.declaration.ClassTreeImpl.accept(ClassTreeImpl.java:198)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:43)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:37)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.visitCompilationUnit(BaseTreeVisitor.java:55)
        at org.sonar.java.checks.UndocumentedApiCheck.visitCompilationUnit(UndocumentedApiCheck.java:98)
        at org.sonar.java.model.JavaTree$CompilationUnitTreeImpl.accept(JavaTree.java:143)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:43)
        at org.sonar.java.checks.UndocumentedApiCheck.scanFile(UndocumentedApiCheck.java:92)
        at org.sonar.java.model.VisitorsBridge.visitFile(VisitorsBridge.java:128)
        at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:84)
        ... 38 more
Caused by: java.io.FileNotFoundException: C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin\mmtel\TAS\.\.sonar\batch-report\issues-31.pb (The pr
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.sonar.scanner.protocol.output.ScannerReportWriter.appendComponentIssue(ScannerReportWriter.java:76)
        ... 65 more
ERROR:
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.

C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin\mmtel\TAS>

**Comment by vishnudesam** [comment]
full error log

ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.squidbridge.api.AnalysisException: SonarQube is unable to analyze file : 'C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin
        at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:93)
        at org.sonar.java.ast.JavaAstScanner.scan(JavaAstScanner.java:67)
        at org.sonar.java.JavaSquid.scanSources(JavaSquid.java:136)
        at org.sonar.java.JavaSquid.scan(JavaSquid.java:129)
        at org.sonar.plugins.java.JavaSquidSensor.analyse(JavaSquidSensor.java:90)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: org.sonar.core.util.ContextException: Unable to write issue | file=C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin\mmtel\TAS\.\.son
        at org.sonar.core.util.ContextException.of(ContextException.java:125)
        at org.sonar.scanner.protocol.output.ScannerReportWriter.appendComponentIssue(ScannerReportWriter.java:79)
        at org.sonar.batch.issue.ModuleIssues.write(ModuleIssues.java:148)
        at org.sonar.batch.issue.ModuleIssues.initAndAddIssue(ModuleIssues.java:97)
        at org.sonar.batch.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:180)
        at org.sonar.api.batch.sensor.issue.internal.DefaultIssue.doSave(DefaultIssue.java:156)
        at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
        at org.sonar.java.JavaIssue.save(JavaIssue.java:80)
        at org.sonar.java.SonarComponents.reportIssueAfterSQ52(SonarComponents.java:231)
        at org.sonar.java.SonarComponents.reportIssue(SonarComponents.java:210)
        at org.sonar.java.model.DefaultJavaFileScannerContext.reportIssue(DefaultJavaFileScannerContext.java:126)
        at org.sonar.java.model.DefaultJavaFileScannerContext.reportIssue(DefaultJavaFileScannerContext.java:121)
        at org.sonar.java.checks.UndocumentedApiCheck.visitNode(UndocumentedApiCheck.java:132)
        at org.sonar.java.checks.UndocumentedApiCheck.visitMethod(UndocumentedApiCheck.java:123)
        at org.sonar.java.model.declaration.MethodTreeImpl.accept(MethodTreeImpl.java:218)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:43)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:37)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.visitClass(BaseTreeVisitor.java:69)
        at org.sonar.java.checks.UndocumentedApiCheck.visitClass(UndocumentedApiCheck.java:110)
        at org.sonar.java.model.declaration.ClassTreeImpl.accept(ClassTreeImpl.java:198)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:43)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:37)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.visitCompilationUnit(BaseTreeVisitor.java:55)
        at org.sonar.java.checks.UndocumentedApiCheck.visitCompilationUnit(UndocumentedApiCheck.java:98)
        at org.sonar.java.model.JavaTree$CompilationUnitTreeImpl.accept(JavaTree.java:143)
        at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:43)
        at org.sonar.java.checks.UndocumentedApiCheck.scanFile(UndocumentedApiCheck.java:92)
        at org.sonar.java.model.VisitorsBridge.visitFile(VisitorsBridge.java:128)
        at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:84)
        ... 38 more
Caused by: java.io.FileNotFoundException: C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin\mmtel\TAS\.\.sonar\batch-report\issues-31.pb (The pr
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.sonar.scanner.protocol.output.ScannerReportWriter.appendComponentIssue(ScannerReportWriter.java:76)
        ... 65 more
ERROR:
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.

C:\Users\reddydv\Downloads\sonar-runner-dist-2.4\sonar-runner-2.4\bin\mmtel\TAS>
