### ISSUE TITLE
sonar-pdf-report is not working with sonarqube 7.0 version. Is this compatibility with sonar 7.0

### ISSUE THREAD

**Issue by p3manas** [SonarQubeCommunity/sonar-pdf-report#36]
I am getting exception 
org.sonar.report.pdf.entity.exception.ReportException: Can't retrieve project info. Parent project node is empty. Authentication?
I have used -Dsonar.pdf.username=admin -Dsonar.pdf.password=admin

**error stacktrace :** 

[DEBUG] 13:43:48.190 Set parameter http.socket.timeout = 30000
[DEBUG] 13:43:48.201 HttpConnectionManager.getConnection:  config = HostConfiguration[host=http://localhost:9000], timeout = 0
[DEBUG] 13:43:48.201 Allocating new connection, hostConfig=HostConfiguration[host=http://localhost:9000]
[DEBUG] 13:43:48.205 Preemptively sending default basic credentials
[DEBUG] 13:43:48.215 Authenticating with BASIC <any realm>@localhost:9000
[DEBUG] 13:43:48.215 Credential charset not configured, using HTTP element charset
[DEBUG] 13:43:48.219 Open connection to localhost:9000
[DEBUG] 13:43:48.280 >> "GET /api/resources?resource=fi.point.merchantserver.monitoring.watchdog%3Awatchdog-common&depth=0&verbose=false& HTTP/1.1[\r][\n]"
[DEBUG] 13:43:48.280 Adding Host request header
[DEBUG] 13:43:48.296 >> "Accept: application/json[\r][\n]"
[DEBUG] 13:43:48.296 >> "Authorization: Basic YWRtaW46YWRtaW4=[\r][\n]"
[DEBUG] 13:43:48.296 >> "User-Agent: Jakarta Commons-HttpClient/3.1[\r][\n]"
[DEBUG] 13:43:48.297 >> "Host: localhost:9000[\r][\n]"
[DEBUG] 13:43:48.297 >> "[\r][\n]"
[DEBUG] 13:43:48.309 << "HTTP/1.1 404 [\r][\n]"
[DEBUG] 13:43:48.309 << "HTTP/1.1 404 [\r][\n]"
[DEBUG] 13:43:48.314 << "Content-Type: application/json[\r][\n]"
[DEBUG] 13:43:48.315 << "Content-Length: 51[\r][\n]"
[DEBUG] 13:43:48.315 << "Date: Tue, 29 May 2018 08:13:47 GMT[\r][\n]"
[DEBUG] 13:43:48.315 << "[\r][\n]"

**org.sonar.report.pdf.entity.exception.ReportException: Can't retrieve project info. Parent project node is empty. Authentication?
	at org.sonar.report.pdf.builder.ProjectBuilder.initializeProject(ProjectBuilder.java:125)
	at org.sonar.report.pdf.PDFReporter.getProject(PDFReporter.java:132)
	at org.sonar.report.pdf.PDFReporter.getReport(PDFReporter.java:83)**
       .......................
[DEBUG] 13:43:48.317 << **"{"errors":[{"msg":"Unknown url : /api/resources"}]}"**
[DEBUG] 13:43:48.317 Resorting to protocol version default close connection policy
[DEBUG] 13:43:48.317 Should NOT close connection, using HTTP/1.1
[DEBUG] 13:43:48.318 Releasing connection back to connection manager.
[DEBUG] 13:43:48.318 Freeing connection, hostConfig=HostConfiguration[host=http://localhost:9000]

**Comment by lkamal** [comment]
I also faced the same issue. Any update on this issue?
